### ISSUE TITLE
Setup continues delivery 

### ISSUE THREAD

**Issue by hepin1989** [reactivemanifesto/website-manifesto#65]
Currently, the webpage is not been updated once we got some updates to this repo?
It would be nice to make it be delivered with a CI.

**Comment by hepin1989** [comment]
@rasummer The Chinese edition need another redeploy:)

**Comment by jroper** [comment]
We're using Heroku, I had a look at enabling the Heroku GitHub automatic deploy integration, but the problem is, it appears that you can't enable without giving Heroku full access to every repository in every organisation you're a part of. That's *way* too much access to give Heroku for just this one deployment, I'm a member of 14 different organisations that it will get access to, some of them private commercial organisations, some of them open source organisations that I have no right to give Heroku access to. I can't enable that.

**Comment by hepin1989** [comment]
Holyshit，Heroku asks too much.
So, how about using a robot account?

**Comment by jroper** [comment]
That may be the best way to do it. I'll look into it.

**Comment by jroper** [comment]
Continuous deployment is now setup. In addition I enabled Travis so that deploy wouldn't be attempted until the code at least compiles. So, after merging a pull request, Travis will go and build the latest master, and once that's successful, Heroku will pick it up and deploy it. In total, deployment happens in less than 10 minutes after pushing to master.
